config/routes.rb
Rails.application.routes.draw do

  root to: 'groups#index'

  get 'search', to: 'groups#index'
  get 'group/:group_urlname/events', to: 'group_events#index', as: :group_events_index

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController

  def index
    @events = Meetup::GroupEventsService.new({
      group_urlname: permitted_params[:group_urlname]
    }).run!.take(3)

    render layout: false
  end

  private

  def permitted_params
    params.permit(:group_urlname)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  LOCATION = 'Munich'

  # Almost always I have in Controller simple actions index, show, update and delete
  # due RESTful approach. May be it would be better to place both controllers to the
  # group folder if we will understand group as the resource.

  def index
    @search_text = permitted_params[:query]
    unless @search_text.nil?
      @groups = Meetup::SearchGroupsService.new({
        text: @search_text,
        location: LOCATION
      }).run!.take(10)
    end
  end

  private

  def permitted_params
    params.permit(:query)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper

  def page_title
    # Its a bit ugly here, I usualliy use gem 'meta-tags', but since it is only two pages...
    ['Meetup client', @search_text, @search_text.nil?? nil : 'Search results'].compact.join(' - ')
  end

end

app/views/group_events/index.html.slim
- @events.each do |event|
  = render partial: 'group_events/index/event', locals: { event: event }

app/views/group_events/index/_event.html.slim
.events-item
  .row
    p.date-time
      = [event[:date], event[:time]].join(' ')
  .row
    p.venue-name
      = event[:venue_name]
  .row
    p.rsvp-count
      = event[:yes_rsvp_count]

app/views/groups/index.html.slim
h1.center-text Meetups client
= form_with url: search_path, method: :get, local: true, skip_enforcing_utf8: true do |form|
  = form.text_field :query, value: @search_text, class: 'query-input'
  = form.submit 'Search', name: nil

.search-results
  - if @groups.present?
    .row.groups-list
      - @groups.each do |group|
        = render partial: 'groups/index/group', locals: { group: group }

    .events[style='display: none;']
      = render partial: 'groups/index/events'

app/views/groups/index/_events.html.slim
.past-events
  h3.center-text Past Events
  h4.meetup_name.center-text
  = link_to 'X', '#', class: 'destroy-past-events'
  .events-list

app/views/groups/index/_group.html.slim
.row.group-item.clearfix
  .thumbnail
    = image_tag group[:thumbnail_photo] if group[:thumbnail_photo].present?
  .description
    .name
      = link_to group[:name], group_events_index_path({group_urlname: group[:urlname]})
    .category-and-status= [group[:category], group[:status]].join(', ')
    .location= group[:location]

app/views/groups/search.html.slim
h1.center-text Meetups client
= form_with url: search_path, method: :get, local: true, skip_enforcing_utf8: true do |form|
  = form.text_field :query, value: @search_text, class: 'query-input'
  = form.submit 'Search', name: nil

.search-results
  - if @groups.present?
    .row.groups-list
      - @groups.each do |group|
        = render partial: 'groups/search/group', locals: { group: group }

    .events

app/views/layouts/application.html.slim
doctype html

html lang='de-DE'
  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    title = page_title

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .content
      = yield